{
 "title": "Asterisk",
 "tags": [ "Asterisk" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Software",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "asterisk_core_properties", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Software version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "asterisk_core_properties", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "asterisk_core_uptime_seconds" }
   ]
  },
  {
   "title": "UDP-address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "asterisk_core_properties", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MAC-address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "asterisk_core_properties", "legendFormat": "{{eid}}" }
   ]
  },
  {
   "title": "Total active abonents",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(asterisk_endpoints_state-1)*100"
    }
   ]
  },
  {
   "title": "Total abonents",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "asterisk_endpoints_count" }
   ]
  },
  {
   "title": "Total active calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "asterisk_calls_count" }
   ]
  },
  {
   "title": "Total active channels",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "asterisk_channels_count" }
   ]
  },
  {
   "title": "Total calls",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "asterisk_calls_sum" }
   ]
  },
  {
   "title": "Last reload",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "asterisk_core_last_reload_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UP/DOWN",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "up{id=\"Asterisk\"}",
     "legendFormat": "-"
    }
   ]
  },
  { "title": "States", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Channels state",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "asterisk_channels_state", "legendFormat": "__auto" },
    {
     "expr": "asterisk_channels_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints state",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "asterisk_endpoints_state" }
   ]
  },
  {
   "title": "Channels duration seconds",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(asterisk_channels_duration_seconds, \"name\", \"$1\", \"name\", \"(.*)-.*\")",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total active sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "asterisk_bridges_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total active channels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "asterisk_channels_count", "legendFormat": "__auto" }
   ]
  }
 ]
}